name: APK Yap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: APK derle
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug

      - name: APK yukle
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
